sylius_grid:
    grids:
        clearis_invoicing_series:
            driver:
                name: doctrine/orm
                options:
                    class: ClearisSylius\InvoicingPlugin\Entity\InvoiceSeries
            sorting:
                code: asc
            limits: [25, 50, 100]
            fields:
                code:
                    type: string
                    label: 'clearis.grid.series.code'
                    sortable: ~
                name:
                    type: string
                    label: 'clearis.grid.series.name'
                type:
                    type: string
                    label: 'clearis.grid.series.type'
                channel:
                    type: twig
                    label: 'clearis.grid.series.channel'
                    path: channel
                    options:
                        template: '@ClearisSyliusInvoicingPlugin/admin/invoice/_partials/channel.html.twig'
                currentNumber:
                    type: string
                    label: 'clearis.grid.series.current_number'
                active:
                    type: twig
                    label: 'clearis.grid.series.active'
                    path: .
                    options:
                        template: '@ClearisSyliusInvoicingPlugin/admin/invoice_series/_active.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
